---
title: "R Notebook"
output: html_notebook
---
Update (August 24, 2026): Cristy added germaria RC counts with late stage counts
July 31, 2026
Graphing of ring canal compositions in late stage follicles using data that Andreana generated
Data is stored on the server at:
smb://anatomyx.ucsf.edu/nystullab/Users/angomez/Ring Canal Project/late stage follicles__pav, vsg, pnut, dapi/pavvsgpnut_latestageRCcounts.csv
 
```{r}
library(tidyverse)
library(ggpubr)
library(ggprism)
```
 
```{r}
GermariumLateStage <- read.csv("../Data/pavvsgpnut_germarium_latestageRCcounts.csv")
```


```{r}
GermariumLateStageSummary <- GermariumLateStage %>% 
  filter(Category != "pnut") %>%
  filter(Category != "pav_pnut")
```

```{r}
GermariumLateStageSummary <- GermariumLateStageSummary %>%
  mutate(
    RCs = recode(Category, "pav_vsg_pnut" = "pav_vsg")) %>% 
  group_by(FileName, Stage, RCs) %>% 
  summarise(
    Count = sum(Count)
  )
```

```{r}
GermariumLateStageSummary <- GermariumLateStageSummary %>% 
  group_by(FileName, Stage) %>% 
  mutate(
    Total = sum(Count),
    Percent = 100* Count / Total
    )
```

```{r}
ggplot(GermariumLateStageSummary, aes(x = RCs, y = Percent, fill= Stage)) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), limits = c(0, 100)) +
  geom_boxplot(aes(color= Stage), fill= "white", outlier.shape = NA) +
  geom_jitter(position= position_jitterdodge(jitter.width= 0.2, dodge.width = 0.75), alpha= 0.8) +
  theme_prism()
```

```{r}
ggsave("../Results/pavvsgpnut_germarium_latestageRCcounts.pdf", width= 6, height= 5)
```

```{r}
LateStageSummary %>% 
  group_by(PavVsg) %>% 
  summarise(
    Mean = mean(Percent),
    SD = sd(Percent)
  )
```

