---
title: "R Notebook"
output: html_notebook
---

July 17, 2026
Analysis of the accuracy of the Stardist models based on manual corrections of
segmentation results from application of the models to the control samples from
the Shrb and Pnut RNAi experiments

```{r}
library(tidyverse)
library(ggprism)
```

```{r}
groundtruth2ch <- read.csv("../Data/groundtruthCountsControls.csv")
groundtruthDAPI <- read.csv("../Data/GroundTruthCountsControls_DAPI_StardistModel.csv")
```

```{r}
#Calculate precision, recall, and F1 for 2ch model
groundtruth2ch$precision <- (groundtruth2ch$ModelTL - groundtruth2ch$FalsePos)/groundtruth2ch$ModelTL
groundtruth2ch$recall <- ((groundtruth2ch$ModelTL - groundtruth2ch$FalsePos)/((groundtruth2ch$ModelTL - groundtruth2ch$FalsePos) + groundtruth2ch$FalseNeg))
groundtruth2ch$F1 <- (2 * groundtruth2ch$precision * groundtruth2ch$recall)/(groundtruth2ch$precision + groundtruth2ch$recall)
```

```{r}
#Calculate precision, recall, and F1 for DAPI
groundtruthDAPI$precision <- (groundtruthDAPI$ModelTL - groundtruthDAPI$FalsePos)/groundtruthDAPI$ModelTL
groundtruthDAPI$recall <- ((groundtruthDAPI$ModelTL - groundtruthDAPI$FalsePos)/((groundtruthDAPI$ModelTL - groundtruthDAPI$FalsePos) + groundtruthDAPI$FalseNeg))
groundtruthDAPI$F1 <- (2 * groundtruthDAPI$precision * groundtruthDAPI$recall)/(groundtruthDAPI$precision + groundtruthDAPI$recall)
```

```{r}
groundtruth2ch_long <- groundtruth2ch %>% 
  select(c("Filename", "precision", "recall", "F1")) %>% 
  pivot_longer(!Filename, names_to = "Metric", values_to = "Value") %>% 
  mutate(Model = "DAPI + Fas3")

groundtruthDAPI_long <- groundtruthDAPI %>% 
  select(c("Filename", "precision", "recall", "F1")) %>% 
  pivot_longer(!Filename, names_to = "Metric", values_to = "Value") %>% 
  mutate(Model = "DAPI only")

groundtruth_long <- rbind(groundtruth2ch_long, groundtruthDAPI_long)
groundtruth_long$Metric <- factor(groundtruth_long$Metric, levels = c("precision", "recall", "F1"))
```

```{r}
groundtruth_long %>% filter(Metric != "F1") %>% 
  ggplot(aes(x = Metric, y = Value, fill = Model)) +
    geom_boxplot() +
    theme_prism()
```

```{r}
groundtruth_long %>% filter(Model == "DAPI + Fas3", Metric != "F1") %>% 
  ggplot(aes(x = Metric, y = Value)) +
  geom_boxplot(fill = "grey") +
  theme_prism() +
  theme(legend.position = "none") + 
  scale_y_continuous(limits = c(0,1)) +
  xlab(NULL) +
  ylab(NULL)
  
ggsave("../Results/StardistAssessment2ch.pdf", width = 100, height = 40, units = "mm")
```

```{r}
groundtruth_long %>% 
  filter(Model == "DAPI + Fas3") %>% 
  group_by(Metric) %>% 
  summarise(Mean= mean(Value), SD = sd(Value))
```